sudo: required

services:
  - docker

env:
  global:
    - REGISTRY=registry.heroku.com
    - NAME=audio2video/web

before_script:
  - docker build . -t ${REGISTRY}/${NAME}

script:
  - docker run ${REGISTRY}/${NAME} bin/phpunit

after_success:
  - if [ "${TRAVIS_PULL_REQUEST}" == "false" ] && [ "{$TRAVIS_BRANCH}" == "wip" ]; then
      docker login -u "${DOCKER_USERNAME}" -p "${DOCKER_PASSWORD}" ${REGISTRY}
      docker push ${REGISTRY}/${NAME}
    fi
