version: '2'
services:
  nginx:
    image: ttskch/nginx-for-silex
    container_name: audio2video_nginx
#    ports:
#      - '8888:80'
#      - '80:80'
    depends_on:
      - php
    volumes:
      - ./docker/nginx:/etc/nginx/conf.d
      - .:/var/www
    environment:
      VIRTUAL_HOST: audio2video.me
      LETSENCRYPT_HOST: audio2video.me
      LETSENCRYPT_EMAIL: kanemoto.takashi+audio2video@gmail.com
    restart: always
  php:
    image: ttskch/php-fpm-for-audio2video
    container_name: audio2video_php
    volumes:
      - .:/var/www
    restart: always
networks:
  default:
    external:
      name: nginxproxy_default
